# This is a basic workflow to help you get started with Actions

name: Build and deploy storybook

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    paths: ["stories/**", "src/**"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  gh-pages:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      
      - name: merge main to gh-pages
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          target_branch: gh-pages
          github_token: ${{ github.token }}
          
      - name: build storybook
        run: |
          git checkout gh-pages
          npm ci
          npm run storybook:build
          git commit -m "Automatic storybook build for ${{ github.sha }}"
          git push origin gh-pages
